// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package roompostgres

import (
	"context"
)

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms (
    id,
    room_number,
    status,
    capacity
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateRoomParams struct {
	ID         string
	RoomNumber string
	Status     string
	Capacity   int32
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom,
		arg.ID,
		arg.RoomNumber,
		arg.Status,
		arg.Capacity,
	)
	return err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT
    id,
    room_number,
    status,
    capacity
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.Status,
		&i.Capacity,
	)
	return i, err
}

const getRooms = `-- name: GetRooms :many
SELECT
    id,
    room_number,
    status,
    capacity
FROM rooms
ORDER BY room_number
`

func (q *Queries) GetRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.RoomNumber,
			&i.Status,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
